.PHONY: default

default:
	python manage.py makemigrations
	python manage.py migrate
	python manage.py adduser

adduser:
	python manage.py adduser

migrations:
	python manage.py makemigrations
	python manage.py migrate

